(defvar x 20)
(defvar y 20)
(defvar ch)
(defvar quit 0)

(defun not (x)
  (if (> x 0) (return 0) (return 1)))

(while (= quit 0)
       ((set ch (getchar))
        (if (= ch "h")
            (set x (- x 1)))
        (if (= ch "j")
            (set y (+ y 1)))
        (if (= ch "k")
            (set y (- y 1)))
        (if (= ch "l")
            (set x (+ x 1)))
        (if (= ch "q")
            (set quit 1))
        (if (= ch "d")
            (print "#"))
        (if (= ch "c")
            (print " "))
        
        (print "\e[" y ";" x "H"))
