int calc_color_bg = 46;
int calc_color_fg = 37; //На практике ни за что не отвечает
int button_color_bg = 107;
int button_color_fg = 30;
int button_color_active_bg = 106;
int button_color_active_fg = 30;
int num_screen_bg = 40;
int num_screen_fg = 37;
int logo_bg = 106;
int logo_fg = 30;
